### ISSUE TITLE
Problem in SFRestRequest after updating SDK from V3.2 to V3.3

### ISSUE THREAD

**Issue by sjacs5537** [forcedotcom/SalesforceMobileSDK-iOS#1102]
I use the code below to post a request which can receive jsonResponse in "didLoadResponse" in V3.2:

SFRestMethod method = SFRestMethodPOST;
SFRestRequest *request = [SFRestRequest requestWithMethod:method path:GET_SALESFORCE_USER_INFO queryParams:[NSDictionary dictionaryWithObject:@"" forKey:@"tMemberId"]];
request.endpoint = DEFAULT_SALESFORCE_REST_API_ENDPOINT;
	
 [[SFRestAPI sharedInstance] send:request delegate:self];

---------------------------------------------------------------------------------
Printing description of request:
<SFRestRequest 0x7fad45891400 
endpoint: /services/apexrest 
method: POST 
path: /GetMemberInfo 
queryParams: {"tMemberId":""} 
>

---------------------------------------------------------------------------------
After I update the SDK to V3.3 and using the same code above, I got the error in "didFailLoadWithError":

Error Domain=CSFNetworkErrorDomain Code=1008 "Processing response content failed" UserInfo=0x7fd12484b490 {action=<SFRestAPISalesforceAction: 0x7fd1227d3210, POST "/GetMemberInfo">, NSLocalizedDescription=Processing response content failed, NSUnderlyingError=0x7fd12484a320 "The operation couldn’t be completed. (Cocoa error 3840.)"}

Does anyone have idea??

**Comment by sjacs5537** [comment]
The issue seems to have been fixed by @bhariharan @khawkins @wmathurin after modifying CSFAction, CSFParameterStorage and SFRestRequest.

I can receive jsonResponse in current unstable branch and this issue can be reproduced in V3.3.

I leave this issue to keep open until the developers make decision.

Thank you.

**Comment by McFlyssss** [comment]
I had a similar issue and the reason was because the Content-Length was not being set up in the request. I could figure it out using Charles.

Try adding
```javascript
 [self setHeaderValue:[@([bodyData length]) stringValue] forHeaderName:@"Content-Length"]; 
```
in SFRestRequest.m line 240

If it's not the same issue I'll open a new one.

Cheers

**Comment by wmathurin** [comment]
Thanks. I believe that's the problem indeed. The fix is already in the unstable branch (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/363f722eed717ef94cecf138aaf9160b09978e80).

**Comment by camflan** [comment]
Still seeing this on ios7 devices,

https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1095
